AWSTemplateFormatVersion: 2010-09-09
Description: |

  Kittens Carousel is a static website application deployed with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.

Resources:
 WebServerInstance:
   Type: AWS::EC2::Instance
   Properties:
    ImageId: ami-0a8b4cd432b1c3063
    InstanceType: t2.micro
    KeyName: firstkey # Please use your own key name without .pem
    SecurityGroups:
      - aa+ssh+http
    Tags:
      -
        Key: Name
        Value: Web_Server_of_StackName
    UserData:
      Fn::Base64: 
        !Sub |
          #! /bin/bash
          yum update -y
          yum install httpd -y
          cd /var/www/html
          wget https://raw.githubusercontent.com/sacide-nur/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
          wget https://raw.githubusercontent.com/sacide-nur/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/sacide-nur/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/sacide-nur/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/sacide-nur/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.png
          systemctl start httpd
          systemctl enable httpd  

 
Outputs:
 WebsiteUrl:
   Description: Kittens Carousel's URL address
   Value: !GetAtt WebServerInstance.PublicDnsName         
 
          
         